fix Error: fatal: unsafe repository ('/__w/jsk_roseus/jsk_roseus' is owned by someone else)
```
  /usr/bin/git init /__w/jsk_roseus/jsk_roseus
  hint: Using 'master' as the name for the initial branch. This default branch name
  hint: is subject to change. To configure the initial branch name to use in all
  hint: of your new repositories, which will suppress this warning, call:
  hint:
  hint: 	git config --global init.defaultBranch <name>
  hint:
  hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
  hint: 'development'. The just-created branch can be renamed via this command:
  hint:
  hint: 	git branch -m <name>
  Initialized empty Git repository in /__w/jsk_roseus/jsk_roseus/.git/
  /usr/bin/git remote add origin https://github.com/jsk-ros-pkg/jsk_roseus
  Error: fatal: unsafe repository ('/__w/jsk_roseus/jsk_roseus' is owned by someone else)
  To add an exception for this directory, call:

  	git config --global --add safe.directory /__w/jsk_roseus/jsk_roseus
```